[package]
name = "liquid_smooth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

fluid = { path = "../fluid"}
nannou = "0.18.1"
rand = "0.8.5"

[profile.release]
opt-level = 1
